# Generated by Django 3.2.15 on 2022-10-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotografiaContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('registro_fotografico_1', models.ImageField(upload_to='fotografia_contexto')),
                ('registro_fotografico_2', models.ImageField(upload_to='fotografia_contexto')),
                ('fecha_registro_fotografico', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fotografia_contexto',
                'verbose_name_plural': 'fotografias_contextos',
            },
        ),
        migrations.CreateModel(
            name='FotografiaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('imagen_fotografia', models.ImageField(upload_to='fotografia_general')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fotografia_general',
                'verbose_name_plural': 'fotografias_generales',
            },
        ),
        migrations.CreateModel(
            name='IdentificacionInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('rol', models.CharField(max_length=50)),
                ('unidad_vecinal', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('VALPARAÍSO', 'Valparaíso')], default='VALPARAÍSO', max_length=50)),
                ('comuna', models.CharField(choices=[('VALPARAÍSO', 'Valparaíso'), ('LAGUNA VERDE', 'Laguna Verde'), ('PLACILLA', 'Placilla'), ('PLAYA ANCHA', 'Playa Ancha')], default='VALPARAÍSO', max_length=50)),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('plan_cerro_poblacion', models.CharField(max_length=255)),
                ('denominacion_inmueble', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'identificacion_inmueble',
                'verbose_name_plural': 'identificaciones_inmuebles',
            },
        ),
        migrations.CreateModel(
            name='InformacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('piso_original_subterraneo', models.CharField(max_length=255)),
                ('piso_original_primer_piso', models.CharField(max_length=255)),
                ('piso_original_pisos_superiores', models.CharField(max_length=255)),
                ('piso_actual_subterraneo', models.CharField(max_length=255)),
                ('piso_actual_primer_piso', models.CharField(max_length=255)),
                ('piso_actual_pisos_superiores', models.CharField(max_length=255)),
                ('anio_construccion', models.CharField(choices=[('ANTERIOR A 1900', 'Anterior a 1900'), ('1901-1920', '1901-1920'), ('1921-1940', '1921-1940'), ('1941-1960', '1941-1960'), ('1961-1970', '1961-1970'), ('1971-1990', '1971-1990'), ('POST 1990', 'Post 1990')], default='ANTERIOR A 1900', max_length=50)),
                ('tipo_propiedad', models.CharField(choices=[('PARTICULAR', 'Particular'), ('FISCAL', 'Fiscal'), ('MUNICIPAL', 'Municipal')], default='PARTICULAR', max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('USUFRUCTUARIO', 'Usufructuario')], default='PROPIETARIO', max_length=50)),
                ('regimen_propiedad', models.CharField(choices=[('INDIVIDUAL', [('PERSONA NATURAL', 'Persona Natural'), ('PERSONA JURIDICA', 'Persona Jurídica')]), ('COLECTIVA', [('COMUNIDAD', 'Comunidad'), ('SUCESION', 'Sucesión')])], default='INDIVIDUAL', max_length=50)),
                ('afectacion_actual', models.CharField(choices=[('DECLARACION DE UTILIDAD PUBLICA', 'Declaración de Utilidad Pública'), ('ANTEJARDIN', 'Antejardín')], default='DECLARACION DE UTILIDAD PUBLICA', max_length=50)),
                ('observaciones', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'informacion_tecnica',
                'verbose_name_plural': 'informaciones_tecnicas',
            },
        ),
        migrations.CreateModel(
            name='PlanoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('imagen_plano', models.ImageField(upload_to='plano_ubicacion')),
                ('latitud', models.CharField(max_length=100)),
                ('longitud', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plano_ubicacion',
                'verbose_name_plural': 'planos_ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='ResenaPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('valor_urbano', models.TextField()),
                ('valor_arquitecnico', models.TextField()),
                ('valor_historico', models.TextField()),
                ('valor_economico_social', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'resena_patrimonial',
                'verbose_name_plural': 'resenas_patrimoniales',
            },
        ),
        migrations.CreateModel(
            name='ValoracionAtributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano', models.PositiveIntegerField(unique=True)),
                ('valor_urbano_a', models.PositiveSmallIntegerField(default=0)),
                ('valor_urbano_b', models.PositiveSmallIntegerField(default=0)),
                ('valor_urbano_c', models.PositiveSmallIntegerField(default=0)),
                ('valor_arquitecnico_a', models.PositiveSmallIntegerField(default=0)),
                ('valor_arquitecnico_b', models.PositiveSmallIntegerField(default=0)),
                ('valor_arquitecnico_c', models.PositiveSmallIntegerField(default=0)),
                ('valor_historico_a', models.PositiveSmallIntegerField(default=0)),
                ('valor_historico_b', models.PositiveSmallIntegerField(default=0)),
                ('valor_historico_c', models.PositiveSmallIntegerField(default=0)),
                ('valor_economico_social_a', models.PositiveSmallIntegerField(default=0)),
                ('valor_economico_social_b', models.PositiveSmallIntegerField(default=0)),
                ('valor_economico_social_c', models.PositiveSmallIntegerField(default=0)),
                ('zona_de_conservacion', models.CharField(max_length=255)),
                ('identificacion_zch', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'valoracion_atributos',
                'verbose_name_plural': 'valoraciones_atributos',
            },
        ),
    ]
