# Generated by Django 3.2.15 on 2022-10-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='autor',
            field=models.CharField(blank=True, default='Se desconoce', max_length=255),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='calle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='denominacion_inmueble',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='plan_cerro_poblacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='rol',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='unidad_vecinal',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_pisos_superiores',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_primer_piso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_actual_subterraneo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_pisos_superiores',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_primer_piso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='piso_original_subterraneo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
