# Generated by Django 3.2.15 on 2022-10-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_1',
            field=models.ImageField(blank=True, default='', upload_to='fotografia_contexto'),
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='registro_fotografico_2',
            field=models.ImageField(blank=True, default='', upload_to='fotografia_contexto'),
        ),
        migrations.AlterField(
            model_name='fotografiageneral',
            name='imagen_fotografia',
            field=models.ImageField(blank=True, default='', upload_to='fotografia_general'),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='afectacion_actual',
            field=models.CharField(blank=True, choices=[('DECLARACION DE UTILIDAD PUBLICA', 'Declaración de Utilidad Pública'), ('ANTEJARDIN', 'Antejardín'), ('OTRO', 'Otro')], default='DECLARACION DE UTILIDAD PUBLICA', max_length=50),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='anio_construccion',
            field=models.CharField(blank=True, choices=[('ANTERIOR A 1900', 'Anterior a 1900'), ('1901-1920', '1901-1920'), ('1921-1940', '1921-1940'), ('1941-1960', '1941-1960'), ('1961-1970', '1961-1970'), ('1971-1990', '1971-1990'), ('POST 1990', 'Post 1990')], default='ANTERIOR A 1900', max_length=50),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='regimen_propiedad',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', [('PERSONA NATURAL', 'Persona Natural'), ('PERSONA JURIDICA', 'Persona Jurídica')]), ('COLECTIVA', [('COMUNIDAD', 'Comunidad'), ('SUCESION', 'Sucesión')])], default='INDIVIDUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='tipo_propiedad',
            field=models.CharField(blank=True, choices=[('PARTICULAR', 'Particular'), ('FISCAL', 'Fiscal'), ('MUNICIPAL', 'Municipal')], default='PARTICULAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('PROPIETARIO', 'Propietario'), ('ARRENDATARIO', 'Arrendatario'), ('USUFRUCTUARIO', 'Usufructuario')], default='PROPIETARIO', max_length=50),
        ),
        migrations.AlterField(
            model_name='planoubicacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, default='', upload_to='plano_ubicacion'),
        ),
        migrations.AlterField(
            model_name='planoubicacion',
            name='latitud',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='planoubicacion',
            name='longitud',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resenapatrimonial',
            name='valor_arquitecnico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resenapatrimonial',
            name='valor_economico_social',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resenapatrimonial',
            name='valor_historico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resenapatrimonial',
            name='valor_urbano',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='identificacion_zch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_arquitecnico_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_arquitecnico_b',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_arquitecnico_c',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_economico_social_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_economico_social_b',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_economico_social_c',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_historico_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_historico_b',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_urbano_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_urbano_b',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='valor_urbano_c',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='zona_de_conservacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
