# Generated by Django 3.2.15 on 2022-12-16 09:16

from django.db import migrations, models
import ficha.models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20221214_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_detalles_constructivos',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_constructivos),
        ),
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_expresion_fachada',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_fachada),
        ),
        migrations.AlterField(
            model_name='caracteristicasmorfologicas',
            name='fotografia_valor_significativo',
            field=models.ImageField(blank=True, null=True, upload_to=ficha.models.content_file_name_significativo),
        ),
    ]
