# Generated by Django 3.2.15 on 2022-10-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20221019_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificacioninmueble',
            name='id',
        ),
        migrations.AlterField(
            model_name='fotografiacontexto',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
        migrations.AlterField(
            model_name='fotografiageneral',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
        migrations.AlterField(
            model_name='identificacioninmueble',
            name='id_plano',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='informaciontecnica',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
        migrations.AlterField(
            model_name='planoubicacion',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
        migrations.AlterField(
            model_name='resenapatrimonial',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
        migrations.AlterField(
            model_name='valoracionatributos',
            name='id_plano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ficha.identificacioninmueble'),
        ),
    ]
