# Generated by Django 3.2.15 on 2022-10-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20221020_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracionatributos',
            name='valor_historico_c',
        ),
    ]
