# Generated by Django 3.2.15 on 2022-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20221216_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='inm_con_his_manzana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='inm_con_his_manzana_enfrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='inm_con_his_predio_contiguo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='inm_con_his_relacion_visual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='mon_his_manzana',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='mon_his_manzana_enfrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='mon_his_predio_contiguo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relaciondelinmuebleconelterreno',
            name='mon_his_relacion_visual',
            field=models.BooleanField(default=False),
        ),
    ]
