# Generated by Django 3.2.15 on 2022-10-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_remove_valoracionatributos_valor_historico_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informaciontecnica',
            name='afectacion_actual',
            field=models.CharField(choices=[('DECLARACION DE UTILIDAD PUBLICA', 'Declaración de Utilidad Pública'), ('ANTEJARDIN', 'Antejardín'), ('OTRO', 'Otro')], default='DECLARACION DE UTILIDAD PUBLICA', max_length=50),
        ),
    ]
